yandex/ch-backup

requirements.txt

It fixes the following error in `main` branch:
```
$ make format
if [ -z "" ]; then python3 -m venv venv; fi
env PATH=venv/bin:/Users/alex-burmak/mdb-scripts/bin:/Users/alex-burmak/ycp/bin:/Users/alex-burmak/yandex-cloud/bin:/Users/alex-burmak/yandex-cloud/bin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/alex-burmak/bin.d/mdb-scripts:/Users/alex-burmak/bin.d/tools:/Users/alex-burmak/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/alex-burmak/go/bin PYTHONIOENCODING=utf8 CLICKHOUSE_VERSION=23.3.7.5 COMPOSE_HTTP_TIMEOUT=300 pip install --no-cache-dir --disable-pip-version-check -r requirements.txt -r requirements-dev.txt …
```

Update max version of PyYAML

---

ch_backup/backup/layout.py
ch_backup/logic/table.py
ch_backup/storage/async_pipeline/base_pipeline/exec_pool.py
ch_backup/storage/async_pipeline/pipeline_executor.py
ch_backup/storage/loader.py
tests/integration/features/backup_restore.feature
tests/integration/modules/ch_backup.py

Respect `--keep-going` flag for async operations. 
This is useful when we want to not stop the restore operation if any error occurs during it. We get the failed restore with the following trace log in a such case:
```
Traceback (most recent call last):
File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/var/tmp/ch-backup/ch_backup/storage/async_pipeline/pipelines.py", line 108, in download_files_pipeline
run(builder.pipeline())
File "/var/tmp/ch-backup/ch_backup/storage/async_pipeline/pipelines.py", line 127, in run
exhaust_iterator(itr)
File "/var/tmp/ch-backup/ch_backup/util.py", line 291, in exhaust_iterator
collections.deque(iterator, maxlen=0)
File …
```

Respect keep-going flag for async operations

---

.github/workflows/link_startrek.yml
README.md

Add continue-on-error and ignoreStatusCodes to link_startrek workflow

---

ch_backup/ch_backup.py
ch_backup/logic/lock_manager.py
tests/integration/features/lock.feature
tests/integration/steps/ch_backup.py

Now in config we can skip locks while schema-only backups.
Setting path in config - `backup: skip_lock_for_schema_only: backup`

Skip locks for schema-only backups via config settings

---

.github/workflows/workflow.yml

Example of artifacts with integration test logs:
https://github.com/yandex/ch-backup/actions/runs/5800651781?pr=37

Upload logs and diagnostics data on Integration test failure

---

tests/integration/modules/zookeeper.py

To avoid adding needless information to behave output.
```
Scenario: check ZK data after restore to replicated storage                                 # tests/integration/features/access_control_replicated_backup.feature:58
Given default configuration                                                               # tests/integration/steps/common.py:12
And a working s3                                                                          # tests/integration/steps/s3.py:11
And a working zookeeper on zookeeper01                                                    # tests/integration/steps/zookeeper.py:13
INFO:kazoo.client:Connecting to 127.0.0.1(127.0.0.1):32833, use_ssl: False
WARNING:kazoo.client:Connection dropped: socket connection error: Connection reset by peer …
```

Disable needless kazoo logging in integration tests

---

README.md

Peer PR for ch-tools repo: https://github.com/yandex/ch-tools/pull/54
Preview:
[![license](https://img.shields.io/github/license/yandex/ch-backup)](https://github.com/yandex/ch-backup/blob/main/LICENSE) [![tests status](https://img.shields.io/github/actions/workflow/status/yandex/ch-backup/.github%2Fworkflows%2Fworkflow.yml?event=push&label=tests&logo=github)](https://github.com/yandex/ch-backup/actions/workflows/workflow.yml?query=event%3Apush) [![chat](https://img.shields.io/badge/telegram-chat-blue)](https://t.me/+O4gURpLnQ604OTE6)

Add badge with link to Telegram chat

---

Makefile
README.md

Use `-` as word separator in all target names. Previously it was used both `_` and `-` as word separators.

Unify naming of Makefile targets

---

requirements-dev.txt

DeepDiff 6.4.0 version contains a bug https://github.com/seperman/deepdiff/issues/415 which breaks our CI

Fix DeepDiff dependency

---

.codespellrc

To avoid failure of `make lint` executed after `make test-integration`.

Add stagging/ to .codespellrc

---

ch_backup/clickhouse/control.py

```
$ ch-backup --port 29443 --config /etc/yandex/ch-backup/ch-backup-schema-copy.conf restore-access-control 9b604b87-8feb-4f50-ad57-bacbbd7271ad; /usr/bin/ch-backup --port 29443 --config /etc/yandex/ch-backup/ch-backup-schema-copy.conf restore 9b604b87-8feb-4f50-ad57-bacbbd7271ad --schema-only
Traceback (most recent call last):
File "/opt/yandex/ch-backup/lib/python3.6/site-packages/ch_backup/clickhouse/client.py", line 64, in query
response.raise_for_status()
File "/opt/yandex/ch-backup/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://sas-t1am73537l8hmc1k.db.yandex.net:29443/?allow_experimental_database_materialized_postgres …
```

Set check_table_dependencies to 0 to avoid HAVE_DEPENDENT_OBJECTS errors in restore

---

ch_backup/storage/engine/s3/s3_engine.py

delete_object should return success if no such object
https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html
but GCP returns error in this case
https://cloud.google.com/storage/docs/xml-api/delete-object

[ORION-3439] Interpter 'NoSuchObject' responce on 'delete_object' as success

---

ch_backup/clickhouse/control.py
ch_backup/logic/table.py
tests/integration/features/backup_restore.feature
tests/integration/steps/s3.py

We got a table based on table function. Example:
```
CREATE table test_pg (id Int, value Int) AS postgresql('localhost:5432', 'test_db', 'test_table', 'test1', '123456')
```
Instead of `posgresql` we can have  [another one](https://clickhouse.com/docs/en/sql-reference/table-functions) which should take data from the remote source, like  `s3` or `redis`.
Scenario:
1. Create backup.
2. Trying to restore to the cluster where data source for the table function is unreachable. 
3. Trying to run a restore again.
Result:
```
Traceback (most recent call last):
File "/usr/local/bin/ch-backup", line 33, in <module>
sys.exit(load_entry_point('ch-backup', 'console_scripts', 'ch-backup')())
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, …
```

Restore retry, when the node have a table based on table function.

---

ch_backup/backup/deduplication.py
ch_backup/backup/layout.py
ch_backup/ch_backup.py
ch_backup/cli.py
ch_backup/clickhouse/client.py
ch_backup/clickhouse/control.py
ch_backup/clickhouse/disks.py
ch_backup/config.py
ch_backup/logging.py
ch_backup/logic/database.py
ch_backup/logic/table.py
ch_backup/logic/udf.py
ch_backup/storage/async_pipeline/base_pipeline/exec_pool.py
ch_backup/storage/pipeline.py
ch_backup/util.py
ch_backup/zookeeper/zookeeper.py
requirements.txt

Changed the `logging` module to `loguru` to provide process-safe logging.

Loguru for logging. 

---

ch_backup/config.py
ch_backup/util.py
requirements-dev.txt

When apply `pylint-3.0.1` got a lot errors like:
```
ch_backup/zookeeper/zookeeper.py:1:0: R0401: Cyclic import (ch_backup.logging -> ch_backup.util) (cyclic-import)
ch_backup/zookeeper/zookeeper.py:1:0: R0801: Similar lines in 2 files
==ch_backup.storage.async_pipeline.stages.filesystem.write_files_stage:[102:143]
==ch_backup.storage.stages.filesystem:[186:226]
buf = self._tarstream.read(self._bytes_to_process)
self._name_from_buffer += buf
self._bytes_to_process -= len(buf)
if self._bytes_to_process > 0:
return False
self._state = State.SKIP_BYTES
if self._tarinfo.size % BLOCKSIZE > 0:
self._bytes_to_process = BLOCKSIZE - (self._tarinfo.size % BLOCKSIZE)
return True
def _process_data(self) -> bool:
assert self._tarinfo
assert self._fobj
buf = self._tarstream.read(self._bytes_to_process) …
```

Fix pylint dependency

---

ch_backup/backup/layout.py
ch_backup/config.py
ch_backup/logic/table.py
ch_backup/logic/upload_part_observer.py
ch_backup/storage/async_pipeline/base_pipeline/exec_pool.py
ch_backup/storage/async_pipeline/pipeline_executor.py
ch_backup/storage/loader.py
tests/unit/test_backup_tables.py
tests/unit/test_upload_part_observer.py

Upload backup metadata with uploaded parts periodically during backup process. Interval of updating is set under `backup` config key `update_metadata_interval`. Default: 30 min.
Problem being solved:
`ch-backup` updates backup metadata in S3 storage after all parts for a table has been uploaded. If creation of backup is stopped unexpectedly (e.g. SIGKILL) all uploaded parts for a table can't be used for deduplication by next backups, because metadata about them was not uploaded.

Upload backup metadata during backup

---

ch_backup/config.py
ch_backup/logic/lock_manager.py

1. Now we try to acquire zk_lock in blocking mode
2. Added configurable timeout after which acquire of lock will be unsuccessful

Add configurable timeout for zk_lock retry

---

ch_backup/cli.py
ch_backup/params.py
tests/unit/test_cli.py

It merges default config + file-config + cli-config.
CLI-config has most priority.
And works like:
```
...
final config after override and merge:  {'backup': {... 'deduplication_age_limit': {'days': 150} ... }}
...
...
final config after override and merge:  {'backup': {... 'deduplication_age_limit': {'days': 150} ... }}
...
#ch-backup --config-value backup '{"deduplication_age_limit": 150, "retain_time": {'days': 150}}' --config-value 'backup:retain_time:days' 300 list
...
final config after override and merge:  {'backup': {... 'deduplication_age_limit': {'days': 150}, 'retain_time': {'days': 300} ... }}
...
```

Add cli parameters to override config value or config section

---

ch_backup/ch_backup.py
ch_backup/clickhouse/control.py
ch_backup/logic/lock_manager.py

Improving logging for lock manager by adding information about shard and replica name on lock acquisition. This would make possible to list the lock contenders on LockTimeout errors, thus helping the investigation of relative issues

Improving logging for lock manager

---

ch_backup/cli.py

It fixes
```
2024-02-17 21:27:53,313 MainProcess 2586266 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-6   2591733 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-8   2591735 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-4   2591731 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-1   2591728 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-2   2591729 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-5   2591732 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-3   2591730 [INFO    ] ch-backup: Received signal %d
2024-02-17 21:27:53,313 Process-7   2591734 [INFO    ] ch-backup: Received signal %d
```

Fixed log record formatting in signal_handler

---

ch_backup/clickhouse/disks.py
ch_backup/config.py
ch_backup/logic/table.py
tests/integration/features/backup_multiple_disks_replicated.feature

Results on large cluster:
```
SELECT
database,
formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
round(usize / size, 2) AS compr_rate,
sum(rows) AS rows,
count() AS part_count
FROM system.parts
WHERE (active = 1) AND (database LIKE 'mdb')
GROUP BY database
ORDER BY size DESC
Query id: bc037387-2b88-45ad-b0c7-da014f3dac30
┌─database─┬─compressed─┬─uncompressed─┬─compr_rate─┬─────────rows─┬─part_count─┐
│ mdb      │ 12.96 TiB  │ 137.44 TiB   │      10.61 │ 544020276855 │       1309 │
└──────────┴────────────┴──────────────┴────────────┴──────────────┴────────────┘
SELECT
database,
formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
formatReadableSize(sum(data_uncompressed_bytes) …
```

Spawn several clickhouse-disks instances for data restoring

---

ch_backup/cli.py
ch_backup/clickhouse/disks.py

`Omitting tmp cloud storage disk cleanup due to exception: "<class 'ch_backup.clickhouse.disks.ClickHouseDisksException'>"` changed to `Omitting tmp cloud storage disk cleanup due to exception: "ClickHouseDisksException: clickhouse-disks call failed with exitcode: 0"`
`Received signal %s` changed to `Received signal 1`

Fix logging

---

ch_backup/clickhouse/control.py
ch_backup/clickhouse/models.py

System.disks table has been changed in 24.3 ClickHouse version. Column `type` is split to three, but we need only two of new columns, so I combined them with `Disk.type` property

Support system.disks for ClickHouse 24.3

---

.ruff.toml

The fix for the following warning:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `.ruff.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'per-file-ignores' -> 'lint.per-file-ignores'
```

Fixed ruff warnings

---

Dockerfile-deb-build

On bionic it fails with:
```
ImportError: /src/debian/ch-backup/opt/yandex/ch-backup/lib/python3.6/site-packages/nacl/_sodium.abi3.so: undefined symbol: crypto_core_ed25519_nonreducedscalarbytes
Makefile:113: recipe for target 'install' failed
```

Revomed usage of system libsodium during PyNaCl installation

---

ch_backup/storage/async_pipeline/pipeline_executor.py

Fix for https://github.com/yandex/ch-backup/pull/108
Before code took memory snapshot after each task in worker, as result time for backups increased in dozens times (like 0.5 second for upload and 10 seconds for snapshot)
This should be in that PR as mentioned in comment "once per 60 seconds", but limit was forgotten in that time.

Set 60 seconds interval between shapshot memory in workers

---

requirements.txt

This reverts commit 3f4b09513c6fef7cd2a476e715cc4fc430ac9524.
boto3 update broke backup creation. 
```
2024-04-28 01:49:10,343 MainProcess 61090 [DEBUG   ] ch-backup: Exponential retry ch_backup.storage.engine.s3.s3_engine.S3StorageEngine.list_dir in 114.20797226824341, attempt: 28, reason
: Failed to make S3 operation: SSL validation failed for https://yandexcloud-dbaas-e4uk0dki9t75jmopn6up.storage.cloud-preprod.yandex.net/?prefix=ch_backup%2Fe4uk0dki9t75jmopn6up%2Fshard1%
2F&delimiter=%2F&encoding-type=url [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
2024-04-28 01:51:04,634 MainProcess 61090 [DEBUG   ] ch-backup: Exponential retry ch_backup.storage.engine.s3.s3_engine.S3StorageEngine.list_dir in 126.46979622430322, attempt: 29, reason
: Failed to make S3 …
```

Revert "Update boto3 requirement from <1.19 to <1.28 (#140)"

---

requirements.txt

Reverts yandex/ch-backup#125
Continuation of https://github.com/yandex/ch-backup/pull/146

Revert "Update botocore requirement from <1.22 to <1.35"

---

.github/workflows/workflow.yml
requirements.txt
setup.py

Just copied already tested by us version of working dependencies for python3.12 from https://github.com/yandex/ch-backup/pull/152/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552
Also added test for the latest CH version.

Added support for python3.12

---

ch_backup/ch_backup.py

Previously it was required to have cloud storage enabled even for `ch-backup restore LAST --udf` command, but cloud storage in that case is not needed

Check cloud storage source bucket if backup contains table data

---

ch_backup/backup/layout.py
ch_backup/storage/engine/base.py
ch_backup/storage/engine/s3/s3_engine.py
ch_backup/storage/loader.py
tests/integration/modules/ch_backup.py

Unescaped paths may cause some errors with s3 client.
Check if escaped path exists is added for backward compatibility with old backups. `path_exists` was working only for files, so I added another method for directories.

Escape database, table and udf names for S3 paths

---

ch_backup/ch_backup.py
ch_backup/clickhouse/client.py

Retries are added in case of OOM on SELECT and something similar, but we decided that retry can be set for every type of exception.

Check if backup name exists and add retry on ClickhouseError for queries

---

ch_backup/logic/table.py
ch_backup/storage/async_pipeline/base_pipeline/exec_pool.py

Using processes with threads leads to deadlock when process inherits the lock that is already acquired by some thread.
By initializing processes before any freeze threads are started we can evade deadlock with logging.

Freeze and backup tables at the same time

---

ch_backup/clickhouse/control.py

`deduplication_info` is a temporal table and recreating it is safe. Also this fixes the case when table schema is changed because before usage it is recreated.

DROP instead of TRUNCATE deduplication_info table

---

ch_backup/logic/table.py

Before raise and log original exception from ClickHouse, let's log database's and table's names.
It seems a problem to find in logs on what table freeze query failed because of parallel execution of freeze queries.

Log table name while freeze exception

---

ch_backup/clickhouse/disks.py
tests/unit/test_disks.py

While restoring cluster we do not need any writes operation to source cluster's cloud storage disk.
So storage credentials could have "Read Only" permission.
But by default CH checks read/write operations to disks while startup - lets skip it.

[MDB-32251] Skip access checks for cloud storage disk of source cluster

---

ch_backup/ch_backup.py
ch_backup/cli.py
ch_backup/clickhouse/metadata_cleaner.py
tests/integration/features/backup_replicated.feature
tests/integration/modules/ch_backup.py

`REPLICA_ONLY` was default option before

Add option to clear all replicas in ZK

---

ch_backup/backup/restore_context.py

We have json with state of each part during restoring the backup and is's quite useful for big backups, helps to determine the current state of the restore(how many parts already restored, how many invalid parts and etc).  
But right now default value for the part state are `INVALID`.  So it is impossible to understand is part really `invalid` or it hasn't downloaded yet.

Added ` NOT_DOWLOADED` state for parts.
